name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Maven 4.1.0-SNAPSHOT
        run: |
          MAVEN_VERSION=4.1.0-SNAPSHOT
          MAVEN_SNAPSHOT_VERSION=4.1.0-20250723.102828-38
          wget https://repository.apache.org/content/repositories/snapshots/org/apache/maven/apache-maven/${MAVEN_VERSION}/apache-maven-${MAVEN_SNAPSHOT_VERSION}-bin.tar.gz
          tar -xzf apache-maven-${MAVEN_SNAPSHOT_VERSION}-bin.tar.gz
          echo "MAVEN_HOME=$(pwd)/apache-maven-${MAVEN_VERSION}" >> $GITHUB_ENV
          echo "$(pwd)/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH




      - name: Build with Maven 4.1.0-SNAPSHOT
        run: mvn clean package

      - name: Verify Maven version
        run: mvn -v

      - name: Build with Mason
        run: mvn clean verify
