name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Maven 4 (RC version)
        run: |
          MAVEN_VERSION=4.0.0-alpha-13
          wget https://dlcdn.apache.org/maven/maven-4/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
          tar -xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz
          echo "MAVEN_HOME=$(pwd)/apache-maven-${MAVEN_VERSION}" >> $GITHUB_ENV
          echo "$(pwd)/apache-maven-${MAVEN_VERSION}/bin" >> $GITHUB_PATH

      - name: Verify Maven version
        run: mvn -v

      - name: Build with Mason
        run: mvn clean verify
