name: CI Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Install Maven 4.1.0-SNAPSHOT
        run: |
          MAVEN_VERSION=4.1.0-SNAPSHOT
          MAVEN_SNAPSHOT_VERSION=4.1.0-20250723.102828-38
          wget https://repository.apache.org/content/repositories/snapshots/org/apache/maven/apache-maven/${MAVEN_VERSION}/apache-maven-${MAVEN_SNAPSHOT_VERSION}-bin.tar.gz
          tar -xzf apache-maven-${MAVEN_SNAPSHOT_VERSION}-bin.tar.gz
          echo "MAVEN_HOME=$(pwd)/apache-maven-4.1.0-SNAPSHOT" >> $GITHUB_ENV
          echo "$(pwd)/apache-maven-4.1.0-SNAPSHOT/bin" >> $GITHUB_PATH

      - name: Enable Mason
        run: |
          mkdir -p .mvn
          echo "polyglot.extensions=io.takari.polyglot.yaml.YamlModelProcessor" > .mvn/extensions.ini

      - name: Build with Mason
        run: mvn clean verify

      - name: Show Maven version
        run: mvn -v

      - name: Login to Azure
        uses: azure/login@v1
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.jar'
